### PR TITLE
Merge back Release 2.0.0

### LINKED ISSUE #104: OpenID Connect 2.0.0
### Reason

- https://github.com/owncloud/openidconnect/pull/103 Azure AD: Use access token payload instead of user info endpoint
- https://github.com/owncloud/openidconnect/pull/112 Message: Object of class OCA\OpenIdConnect\Application could not be converted to string
- https://github.com/owncloud/openidconnect/pull/85 Import user from openid provider: Auto provisioning mode

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" https://github.com/owncloud/openidconnect/issues/132

### Documentation

- [x] :x: Changes in the docs needed? If so create issue in owncloud/docs. :x: -> https://github.com/owncloud/docs/pull/2447

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date --> https://github.com/owncloud/administration-internal/pull/223

### PR DESCRIPTION
**Pull request by jnweiger**
Closes #104

### CODE REVIEW

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
I hope we will get a clean commit history before the merge .....

**Comment by jnweiger** [comment]
> I hope we will get a clean commit history before the merge .....

Same discussion every time. I cannot do that. Sorry.

**Comment by DeepDiver1975** [comment]
> Same discussion every time. I cannot do that. Sorry. Github does it.

learn it - https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by micbar** [comment]
Please merge it now

**Review by micbar — APPROVED** [review]

**Pull request merged**
